-- [SCLIBRARY] - Define the user/schema to be used for SmarterCommerce
-- Replace the tags in the script below using these guidelines

CREATE OR REPLACE PACKAGE [SCLIBRARY]."GLOBALPKG" AS
 TYPE refcursor IS REF CURSOR;
END;
/




-- Create Tables Section

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].CMM_GETGNRLANNOUNCEASSIGNLST_A 
	( "ANNOUNCEMENTID" NUMBER, "UNIQUEKEYID" NUMBER, "ASSIGNMENTTYPE" NUMBER,
	"ASSIGNMENTVALUE" NVARCHAR2(40), "DESCRIPTION" NVARCHAR2(256),"CATEGORYCODE" NCHAR(10) )  
 ON COMMIT PRESERVE ROWS;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].CMM_GETUSERANNOUNCEMENTLIST_A
	("MS$9NID" NUMBER)
 ON COMMIT PRESERVE ROWS;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].CMM_GETUSERANNOUNCEMENTLIST_B 
  ("ANNOUNCEMENTID" NUMBER)  
 ON COMMIT PRESERVE ROWS;
  /
-- Create Tables Section

--INV_EXCITEMCATCODEVALIDATION
 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_EXCITEMCATCODEVALIDAT_A
    ("CATEGORY" NCHAR(15))
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATALOGLIST_A ("CATALOGID"
    NVARCHAR2(3), "EFFECTIVEMODEFLAG" NUMBER, "EFFECTIVEFROMDATE"
    NUMBER, "EFFECTIVETHRUDATE" NUMBER, "DESCRIPTION"
    NVARCHAR2(30), "SEQUENCENUMBER" NUMBER, "INSTALLATIONID"
    NVARCHAR2(3), "MCU" NVARCHAR2(12), "MCUBEHAVIOR" NVARCHAR2(1))
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATNODEITEMATTLIST_C
    ("INSTALLATIONID" NVARCHAR2(3), "BRANCHPLANT" NVARCHAR2(12),
    "BRANCHPLANTDESC" NVARCHAR2(30), "ITEMNUMBER" NUMBER,
    "LONGITEMNUMBER" NVARCHAR2(25), "AUXITEMNUMBER" NVARCHAR2(25),
    "DESCRIPTION1" NVARCHAR2(30), "DESCRIPTION2" NVARCHAR2(30),
    "PRIMARYUNITOFMEASURE" NVARCHAR2(2), "SECONDARYUNITOFMEASURE"
    NVARCHAR2(2), "PRICINGUNITOFMEASURE" NVARCHAR2(2),
    "SEARCHITEMTEXT" NVARCHAR2(30), "STOCKINGTYPE" NVARCHAR2(1),
    "LINETYPE" NVARCHAR2(2), "INVENTORYFLAG" NVARCHAR2(1),
    "ITEMFLASHMESSAGE" NVARCHAR2(2), "DISPLAYITEMNUMBER"
    NVARCHAR2(25), "PRIORITY" NUMBER, "URL" NVARCHAR2(256),
    "REFPRODUCTNUMBER" NVARCHAR2(25))
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCOOKIECRUMB_A ("CATALOGID"
    NVARCHAR2(3), "CATALOGDETAILID" NUMBER, "PARENTKEYID" NUMBER,
    "DESCRIPTION" NVARCHAR2(30), "INCLUDEINSEARCH" NUMBER,
    "DATAITEM" NVARCHAR2(10), "USERDEFINEDCODE" NVARCHAR2(10),
    "TEMPLATEID" NVARCHAR2(10))
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMASSOCIATEDLIST_A
    ("ITEMNUMBER" NUMBER, "LONGITEMNUMBER" NCHAR(25),
    "AUXITEMNUMBER" NCHAR(25), "REFPRODUCTNUMBER" NCHAR(25),
    "DESCRIPTION1" NCHAR(30), "DESCRIPTION2" NCHAR(30),
    "PRIMARYUNITOFMEASURE" NCHAR(2), "SECONDARYUNITOFMEASURE"
    NCHAR(2), "PRICINGUNITOFMEASURE" NCHAR(2),
    "STOCKINGTYPE" NCHAR(1), "LINETYPE" NCHAR(2),
    "INVENTORYFLAG" NCHAR(1))
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMASSOCIATEDLIST_B
    ("ITEMNUMBER" NUMBER, "LONGITEMNUMBER" NCHAR(25),
    "AUXITEMNUMBER" NCHAR(25), "REFPRODUCTNUMBER" NCHAR(25),
    "DESCRIPTION1" NCHAR(30), "DESCRIPTION2" NCHAR(30),
    "PRIMARYUNITOFMEASURE" NCHAR(2), "SECONDARYUNITOFMEASURE"
    NCHAR(2), "PRICINGUNITOFMEASURE" NCHAR(2),
    "STOCKINGTYPE" NCHAR(1), "LINETYPE" NCHAR(2),
    "INVENTORYFLAG" NCHAR(1))
   ON COMMIT PRESERVE ROWS ;

--INV_GetItemMasterCatalogedList
 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMASTERCATALIST_A
    ("INSTALLATIONID" NVARCHAR2(3), "ITEMNUMBER" NUMBER,
    "LONGITEMNUMBER" NVARCHAR2(25), "AUXITEMNUMBER" NVARCHAR2(25),
    "DESCRIPTION1" NVARCHAR2(30), "DESCRIPTION2" NVARCHAR2(30),
    "PRIMARYUNITOFMEASURE" NVARCHAR2(2), "SECONDARYUNITOFMEASURE"
    NVARCHAR2(2), "PRICINGUNITOFMEASURE" NVARCHAR2(2),
    "SEARCHITEMTEXT" NVARCHAR2(30), "STOCKINGTYPE" NVARCHAR2(1),
    "LINETYPE" NVARCHAR2(2), "INVENTORYFLAG" NVARCHAR2(1),
    "ITEMFLASHMESSAGE" NVARCHAR2(2), "DISPLAYITEMNUMBER"
    NVARCHAR2(25))
   ON COMMIT PRESERVE ROWS ;

--INV_GetItemMasterInfoUnknown
 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMASTINFUNKNOWN_A
    ("INSTALLATIONID" NVARCHAR2(3), "BRANCHPLANT" NVARCHAR2(12),
    "BRANCHPLANTDESC" NVARCHAR2(30), "ITEMNUMBER" NUMBER,
    "LONGITEMNUMBER" NVARCHAR2(25), "AUXITEMNUMBER" NVARCHAR2(25),
    "DESCRIPTION1" NVARCHAR2(30), "DESCRIPTION2" NVARCHAR2(30),
    "URL" NVARCHAR2(256), "PRIMARYUNITOFMEASURE" NVARCHAR2(2),
    "SECONDARYUNITOFMEASURE" NVARCHAR2(2), "PRICINGUNITOFMEASURE"
    NVARCHAR2(2), "SEARCHITEMTEXT" NVARCHAR2(30), "STOCKINGTYPE"
    NVARCHAR2(1), "LINETYPE" NVARCHAR2(2), "INVENTORYFLAG"
    NVARCHAR2(1), "ITEMFLASHMESSAGE" NVARCHAR2(2), "MATRIXTEMPLATE" NVARCHAR2(20),
	"MATRIXCONTROLLED" NVARCHAR2(1), "MATRIXPARENTITEMNUMBER" NUMBER,
	"ADDRESSNUMBER" NUMBER,
	"ALLOWPICKUP" NVARCHAR2(1),
	"CYCL" NCHAR(3),
	"PRP0" NCHAR(6),
	"PRP1" NCHAR(3),
	"PRP2" NCHAR(3),
	"PRP3" NCHAR(3),
	"PRP4" NCHAR(3),
	"PRP5" NCHAR(3),
	"PRP6" NCHAR(6),
	"PRP7" NCHAR(6),
	"PRP8" NCHAR(6),
	"PRP9" NCHAR(6),
	"SHCM" NCHAR(3),
	"SHCN" NCHAR(3),
	"SRP0" NCHAR(6),
	"SRP1" NCHAR(3),
	"SRP2" NCHAR(3),
	"SRP3" NCHAR(3),
	"SRP4" NCHAR(3),
	"SRP5" NCHAR(3),
	"SRP6" NCHAR(6),
	"SRP7" NCHAR(6),
	"SRP8" NCHAR(6),
	"SRP9" NCHAR(6) )
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMASTERLIST_A
   ("ITEMNUMBER" NUMBER, "LONGITEMNUMBER" NCHAR(25), "AUXITEMNUMBER"  NCHAR(25),
	"DESCRIPTION1"  NCHAR(30), "DESCRIPTION2"  NCHAR(30),
	"PRIMARYUNITOFMEASURE"  NCHAR(2), "SECONDARYUNITOFMEASURE" NCHAR(2),
	"PRICINGUNITOFMEASURE" NCHAR(2),	"SEARCHITEMTEXT" NCHAR(30),"STOCKINGTYPE" NCHAR(1), "LINETYPE" NCHAR(2),
	"INVENTORYFLAG" NCHAR(1), "ITEMFLASHMESSAGE" NCHAR(2), "MATRIXTEMPLATE" NCHAR(20), "MATRIXCONTROLLED" NCHAR(1))
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMASTERLIST_B
    ("ITEMNUMBER" NUMBER, "LONGITEMNUMBER" NCHAR(25), "AUXITEMNUMBER"  NCHAR(25),
	"DESCRIPTION1"  NCHAR(30), "DESCRIPTION2"  NCHAR(30),
	"PRIMARYUNITOFMEASURE"  NCHAR(2), "SECONDARYUNITOFMEASURE" NCHAR(2),
	"PRICINGUNITOFMEASURE" NCHAR(2),	"SEARCHITEMTEXT" NCHAR(30),"STOCKINGTYPE" NCHAR(1), "LINETYPE" NCHAR(2),
	"INVENTORYFLAG" NCHAR(1), "ITEMFLASHMESSAGE" NCHAR(2), "MATRIXTEMPLATE" NCHAR(20),
	"MATRIXCONTROLLED" NCHAR(1))
   ON COMMIT PRESERVE ROWS ;

--INV_GetItemMsterWebCatalogList
 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMSTEWEBCATLIST_C
    ("DESCRIPTION" NVARCHAR2(30), "ATTRIBUTEVALUE" NVARCHAR2(256))
   ON COMMIT PRESERVE ROWS ;

--INV_GetItemWebContentHeadList
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMWEBCONHEADLIST_A 
(
	"TBLITEMNUMBER" NUMBER, 
	"TBLINSTALLATIONID" NCHAR(3), 
	"DESIGNSTATUS" NUMBER, 
	LongItemNumber NCHAR(25),
	AuxItemNumber NCHAR(25),
	"DESCRIPTION1" NCHAR(30), 
	"DESCRIPTION2" NCHAR(30), 
	"DESCRIPTION3" NCHAR(30), 
	"PUBLISHEDSINCE" NUMBER, 
	DRAFTANDPUBLISHED NUMBER 
)
ON COMMIT PRESERVE ROWS;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMWEBCONHEADLIST_B ("TBLITEMNUMBER"
    NUMBER, "DISPLAYITEMNUMBER" NVARCHAR2(25),"TBLINSTALLATIONID" NVARCHAR2(3), "DESIGNSTATUS" NUMBER, "DESCRIPTION1" NVARCHAR2(30), "DESCRIPTION2"
    NVARCHAR2(30), "DESCRIPTION3" NVARCHAR2(30), "PUBLISHEDSINCE" NUMBER, DRAFTANDPUBLISHED NUMBER )
   ON COMMIT PRESERVE ROWS ;

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATALOGTREE_A ("UNIQUEKEYID"
    NUMBER, "CATALOGID" NVARCHAR2(50), "PARENTKEYID" NUMBER,
    "DESCRIPTION" NVARCHAR2(30), "SEQNUMBER" NUMBER)
   ON COMMIT PRESERVE ROWS ;

  CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATALOGASSIGLISTCC_A (
	"CATALOGID" NCHAR(3), 
	"CATALOGNAME" NCHAR(30), 
	"EFFECTIVEMODEFLAG" NUMBER,
    "EFFECTIVEFROMDATE" NUMBER, 
	"EFFECTIVETHRUDATE" NUMBER,
	"DESCRIPTION" NCHAR(30), 
	"SEQUENCENUMBER" NUMBER,
    "INSTALLATIONID" NCHAR(3), 
	"MCU" NCHAR(12), 
	"MCUBEHAVIOR" NCHAR(1)
	)
   ON COMMIT PRESERVE ROWS ;


   CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATALOGASSIGLIST_A
    ("DATAITEM" NVARCHAR2(10))
   ON COMMIT PRESERVE ROWS ;

   --INV_GetCatalogNodeItems
	CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATALOGNODEITEMS_A 
	(
		"CATALOGID"			NCHAR(3), 
		"UNIQUEKEYID"		NUMBER, 
		"ITEMNUMBER"		NUMBER,
		"LONGITEMNUMBER"	NCHAR(25), 
		"AUXITEMNUMBER"		NCHAR(25),
		"DESCRIPTION1"		NCHAR(30), 
		"DESCRIPTION2"		NCHAR(30),
		"SEQUENCENUMBER"	NUMBER, 
		"INVENTORYFLAG"		NCHAR(1),
		"STOCKINGTYPE"		NCHAR(1),
		"SCTYPE"			NCHAR(1),
		"TEMPLATE"			NCHAR(20),
		"SEGMENT1"			NCHAR(10)
	)
	ON COMMIT PRESERVE ROWS;


   --INV_GetCatNodeItemsNotRel
   CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATNODEITEMSNOTREL_A ("ITEMNUMBER" NUMBER,
    "LONGITEMNUMBER" NCHAR(25), "AUXITEMNUMBER" NCHAR(25), "DISPLAYITEMNUMBER" NCHAR(25),
    "DESCRIPTION1" NCHAR(30), "DESCRIPTION2" NCHAR(30),
    "INVENTORYFLAG" NCHAR(1), "STOCKINGTYPE" NCHAR(1), "DESIGNSTATUS" NUMBER, "SCTYPE" NCHAR(1),"TEMPLATE" NCHAR(20))
   ON COMMIT PRESERVE ROWS;

   --INV_GetCatNodeItemsNotRel Paging
   CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATNODEITEMSNOTREL_B ("ITEMNUMBER" NUMBER,
    "LONGITEMNUMBER" NCHAR(25), "AUXITEMNUMBER" NCHAR(25),
    "DESCRIPTION1" NCHAR(30), "DESCRIPTION2" NCHAR(30),
	"DISPLAYITEMNUMBER" NCHAR(25), "INVENTORYFLAG" NCHAR(1),
	"STOCKINGTYPE" NCHAR(1), "SCTYPE" NCHAR(1),"TEMPLATE" NCHAR(20))
   ON COMMIT PRESERVE ROWS;

/*Catalog NSM Temporary Tables*/
 --Node leaves temporary table
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_EXGETCATNODXMLITMLST_A ("NODEID" NUMBER,
	"TEMPLATEID" NCHAR(10), 
	"PARENTID" NUMBER,
	"RANKNODE" NUMBER,
	"INCLUDEINSEARCH" NUMBER,
	"EFFECTIVETHRUDATE" NUMBER,
	"EFFECTIVEMODEFLAG" NUMBER
	)
   ON COMMIT PRESERVE ROWS;
   CREATE INDEX [SCLIBRARY].INV_EXGETCATNODXMLITMLST_A ON [SCLIBRARY].INV_EXGETCATNODXMLITMLST_A(RANKNODE);

 --ITEMSTABLE data temporary table, Contains all items related directly with a catalog node, without Matrix children
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_EXGETCATNODXMLITMLST_B ("ITEMNUMBER" NUMBER,
	"SCTYPE" NCHAR(1), 
	"TEMPLATE" NCHAR(20), 
	"SEGMENT1" NCHAR(10))
   ON COMMIT PRESERVE ROWS;
   CREATE INDEX [SCLIBRARY].INV_EXGTCATNODEXMLITMLST_IDXB ON [SCLIBRARY].INV_EXGETCATNODXMLITMLST_B(ITEMNUMBER);
   CREATE INDEX [SCLIBRARY].INV_EXGTCATNODEXMLITMLST_IDXBT ON [SCLIBRARY].INV_EXGETCATNODXMLITMLST_B(SCTYPE);

--NodeItems data temporary table
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_EXGETCATNODXMLITMLST_C ("NODEID" NUMBER,
	"ITEMNUMBER" NUMBER, "PRIORITY"  NUMBER)
   ON COMMIT PRESERVE ROWS;

--TEMPORARY ITEMS temporary table
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_EXGETCATNODXMLITMLST_D ("ITEMNUMBER" NUMBER,
	"PRIORITY" NCHAR(25),
	"SCTYPE" NCHAR(1),
	"TEMPLATE" NCHAR(20), 
	"SEGMENT1" NCHAR(10))
   ON COMMIT PRESERVE ROWS;
   CREATE INDEX [SCLIBRARY].INV_EXGETCATNODXMLITMLST_IDXD ON [SCLIBRARY].INV_EXGETCATNODXMLITMLST_D(ITEMNUMBER);

--INV_ExcGetCatNodeXMLItemList, TEMPORARY final table with items informations included matrix children items.
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_EXGETCATNODXMLITMLST_I (
	"ITEMNUMBER" NUMBER,
	"DESCRIPTION1"  NCHAR(30),
	"DESCRIPTION2"  NCHAR(30),
	"DESCRIPTION3"  NCHAR(30),
	"BRANCHPLANT" NCLOB,
	"PRIMARYUNITMEASURE" NCHAR(2),
	"PRICINGUNITMEASURE" NCHAR(2),
	"SHIPPINGUNITMEASURE" NCHAR(2),
	"CONTENT" NCLOB,
	"INVENTORYFLAG" NCHAR(1),
	"CROSSREFERENCE" NCLOB,
	"LONGITEMNUMBER" NCHAR(25),
	"AUXILIARYITEMNUMBER" NCHAR(25),
	"STOCKINGTYPE" NCHAR(1),
	"INSTALLATIONID" NCHAR(3),
	"SCTYPE" NCHAR(1),
	"TEMPLATE" NCHAR(20))
   ON COMMIT PRESERVE ROWS;
   CREATE INDEX [SCLIBRARY].INV_EXGTCATNODEXMLITMLST_IDXI ON [SCLIBRARY].INV_EXGETCATNODXMLITMLST_I(ITEMNUMBER);


--INV_GetKitComponentsList
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETKITCOMPONENTSLIST_A (
	"PARENTITEMNUMBER" NUMBER, 
	"FEATUREPARENTITEM" NUMBER, 
	"COMPONENTITEMNUMBER" NUMBER,
	"COMPONENTLINENUMBER" NUMBER, 
	"COMPONENTTYPE" NCHAR(1),
	"REQUIRED" NCHAR(1), 
	"QUANTITY" NUMBER, 
	"UNITOFMEASURE" NCHAR(2))
ON COMMIT PRESERVE ROWS;

--INV_GetCatalogNodeListFnc
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATALOGNODELISTFNC_A
(
	"CATALOGID"	NCHAR(3), 
	"UNIQUEKEYID" NUMBER,
	"PARENTKEYID" NUMBER, 
	"INCLUDEINSEARCH" NUMBER,
	"DESCRIPTION" NCHAR(30),
	"EFFECTIVEMODEFLAG"	NUMBER,
	"EFFECTIVEFROMDATE"	NUMBER,	
	"EFFECTIVETHRUDATE"	NUMBER,
	"SEQUENCENUMBER" NUMBER,
	"IMAGENAME"	NVARCHAR2(256),
	"TEMPLATEID"  NCHAR(10)
)
ON COMMIT PRESERVE ROWS;

-- INV_GetItemMasterContentList
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMASTERCONTLIST_A("ITEMNUMBER" NUMBER,
	"LONGITEMNUMBER" NVARCHAR2(25),  "AUXITEMNUMBER" NVARCHAR2(25), "DESCRIPTION1" NVARCHAR2(30),
	"DESCRIPTION2" NVARCHAR2(30), "DESCRIPTION3" NVARCHAR2(30), "PRIMARYUNITOFMEASURE" NVARCHAR2(2),
	"SECONDARYUNITOFMEASURE" NVARCHAR2(2), "PRICINGUNITOFMEASURE" NVARCHAR2(2), "SEARCHITEMTEXT" NVARCHAR2(30),
	"STOCKINGTYPE" NVARCHAR2(1), "LINETYPE" NVARCHAR2(2), "INVENTORYFLAG" NVARCHAR2(1), "ITEMFLASHMESSAGE" NVARCHAR2(2),
	"CONTENTINSTALLATIONID" NVARCHAR2(3), "DESIGNSTATUS" NUMBER, "CONTAINSCONTENT" NVARCHAR2(2))
ON COMMIT PRESERVE ROWS ;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMASTERCONTLIST_B("ITEMNUMBER" NUMBER,
	"LONGITEMNUMBER" NVARCHAR2(25),  "AUXITEMNUMBER" NVARCHAR2(25), "DESCRIPTION1" NVARCHAR2(30),
	"DESCRIPTION2" NVARCHAR2(30), "DESCRIPTION3" NVARCHAR2(30), "PRIMARYUNITOFMEASURE" NVARCHAR2(2),
	"SECONDARYUNITOFMEASURE" NVARCHAR2(2), "PRICINGUNITOFMEASURE" NVARCHAR2(2), "SEARCHITEMTEXT" NVARCHAR2(30),
	"STOCKINGTYPE" NVARCHAR2(1), "LINETYPE" NVARCHAR2(2), "INVENTORYFLAG" NVARCHAR2(1), "ITEMFLASHMESSAGE" NVARCHAR2(2),
	"CONTENTINSTALLATIONID" NVARCHAR2(3), "DESIGNSTATUS" NUMBER, "CONTAINSCONTENT" NVARCHAR2(2))
ON COMMIT PRESERVE ROWS ;


--INV_GetCatalogNodeItemList
 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETCATNODEITEMLIST_A
    ("ITEMNUMBER" NUMBER, LongItemNumber NCHAR(25), AuxItemNumber NCHAR(25), "DESCRIPTION1" NCHAR(30), 
	"DESCRIPTION2" NCHAR(30), "SEARCHTEXT" NCHAR(300), "TEMPLATE" NCHAR(20), "SEGMENT1" NCHAR(10), "MATRIXCONTROLLED" NCHAR(1))
   ON COMMIT PRESERVE ROWS ;

/* INV_ExcGetItemXMLList */
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_EXCGETITEMXMLLIST_A
( 
	ShortItemNumber		NUMBER,
	TBLInstallationID	NCHAR(3)
)
 ON COMMIT PRESERVE ROWS;

--INV_GetProdPublishBasicDetail, TEMPORARY final table with items informations.
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETPRODPUBLISHBASIC_A (
	"SHORTPRODUCTNUMBER"		NUMBER,	
	"LONGPRODUCTNUMBER"		NCHAR(25),	
	"AUXILIARYPRODUCTNUMBER"	NCHAR(25),
	"DESCRIPTION1"				NCHAR(30),
	"DESCRIPTION2"				NCHAR(30),
	"STOCKINGTYPE"				NCHAR(1),
	"INVENTORYFLAG"				NCHAR(1),
	"LINETYPE"					NCHAR(2),
	"PRIMARYUOM"				NCHAR(2),	
	"PRICINGUOM"				NCHAR(2),	
	"SHIPPINGUOM"				NCHAR(2),
	"ABCCODESALES"				NCHAR(1),
	"ABCCODEMARGIN"				NCHAR(1),
	"ABCCODEINVESTMENT"			NCHAR(1),
	"UPCNUMBER"					NCHAR(13),
	"SCTYPE"					NCHAR(1),	
	"MATRIXTEMPLATE"			NCHAR(20),	
	"MATRIXCONTROLLED"			NCHAR(1),
	"SEGMENT1"					NCHAR(10),
	"CYCLECOUNTCATEGORY"		NCHAR(3),	
	"CATEGORYCODE10"			NCHAR(6),	
	"CATEGORYCODE1"				NCHAR(3),
	"CATEGORYCODE2"				NCHAR(3),
	"CATEGORYCODE3"				NCHAR(3),
	"CATEGORYCODE4"				NCHAR(3),
	"CATEGORYCODE5"				NCHAR(3),
	"CATEGORYCODE6"				NCHAR(6),
	"CATEGORYCODE7"				NCHAR(6),
	"CATEGORYCODE8"				NCHAR(6),
	"CATEGORYCODE9"				NCHAR(6),
	"SHIPPINGCOMMODITYCLASS"	NCHAR(3),
	"SHIPPINGCONDITIONSCODE"	NCHAR(3),
	"SALESCODE10"				NCHAR(6),
	"SALESCODE1"				NCHAR(3),	
	"SALESCODE2"				NCHAR(3),	
	"SALESCODE3"				NCHAR(3),	
	"SALESCODE4"				NCHAR(3),	
	"SALESCODE5"				NCHAR(3),
	"SALESCODE6"				NCHAR(6),	
	"SALESCODE7"				NCHAR(6),
	"SALESCODE8"				NCHAR(6),	
	"SALESCODE9"				NCHAR(6),
	"SEARCHTEXT"				NCHAR(30),
	"STANDARDUNITOFMEASURE"		NCHAR(2),
	"TOTALROWCOUNT"				INT
)
   ON COMMIT PRESERVE ROWS;
   CREATE INDEX [SCLIBRARY].INV_GETPRODPUBLISHBASIC_IDXI ON [SCLIBRARY].INV_GETPRODPUBLISHBASIC_A(SHORTPRODUCTNUMBER);

--INV_GetItemPublishDetail, TEMPORARY final table with items informations.
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETPRODPUBLISHDETAIL_A (
	"SHORTPRODUCTNUMBER"			NUMBER,	
	"LONGPRODUCTNUMBER"			NCHAR(25),	
	"AUXILIARYPRODUCTNUMBER"		NCHAR(25),
	"DESCRIPTION1"				NCHAR(30),
	"DESCRIPTION2"				NCHAR(30),
	"STOCKINGTYPE"				NCHAR(1),
	"INVENTORYFLAG"				NCHAR(1),
	"LINETYPE"					NCHAR(2),
	"PRIMARYUOM"				NCHAR(2),	
	"PRICINGUOM"				NCHAR(2),	
	"SHIPPINGUOM"				NCHAR(2),
	"ABCCODESALES"				NCHAR(1),
	"ABCCODEMARGIN"				NCHAR(1),
	"ABCCODEINVESTMENT"			NCHAR(1),
	"UPCNUMBER"					NCHAR(13),
	"SCTYPE"					NCHAR(1),	
	"MATRIXTEMPLATE"			NCHAR(20),	
	"MATRIXCONTROLLED"			NCHAR(1),
	"SEGMENT1"					NCHAR(10),
	"CYCLECOUNTCATEGORY"		NCHAR(3),	
	"CATEGORYCODE10"			NCHAR(6),	
	"CATEGORYCODE1"				NCHAR(3),
	"CATEGORYCODE2"				NCHAR(3),
	"CATEGORYCODE3"				NCHAR(3),
	"CATEGORYCODE4"				NCHAR(3),
	"CATEGORYCODE5"				NCHAR(3),
	"CATEGORYCODE6"				NCHAR(6),
	"CATEGORYCODE7"				NCHAR(6),
	"CATEGORYCODE8"				NCHAR(6),
	"CATEGORYCODE9"				NCHAR(6),
	"SHIPPINGCOMMODITYCLASS"	NCHAR(3),
	"SHIPPINGCONDITIONSCODE"	NCHAR(3),
	"SALESCODE10"				NCHAR(6),
	"SALESCODE1"				NCHAR(3),	
	"SALESCODE2"				NCHAR(3),	
	"SALESCODE3"				NCHAR(3),	
	"SALESCODE4"				NCHAR(3),	
	"SALESCODE5"				NCHAR(3),
	"SALESCODE6"				NCHAR(6),	
	"SALESCODE7"				NCHAR(6),
	"SALESCODE8"				NCHAR(6),	
	"SALESCODE9"				NCHAR(6),
	"STANDARDUNITOFMEASURE"		NCHAR(2),
	"SEARCHTEXT"				NCHAR(30),
	"TOTALROWCOUNT"				INT
)
   ON COMMIT PRESERVE ROWS;
   CREATE INDEX [SCLIBRARY].INV_GETPRODPUBLISHDETAIL_IDXI ON [SCLIBRARY].INV_GETPRODPUBLISHDETAIL_A(SHORTPRODUCTNUMBER);

--INV_GetItemPublishDetail, TEMPORARY final table with items informations.
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETPRODPUBLISHDETAIL_B (
	"SHORTPRODUCTNUMBER"			NUMBER,	
	"UNITOFMEASURE"				NCHAR(3)
)
   ON COMMIT PRESERVE ROWS;

--INV_GetItemMatrixChildren, TEMPORARY final table with items informations.
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].INV_GETITEMMATRIXCHILDREN_A (
	"ITEMNUMBER"			NUMBER,	
	"PARENTITEMNUMBER"		NUMBER
)
   ON COMMIT PRESERVE ROWS;
   CREATE INDEX [SCLIBRARY].INV_GETITEMMATRIXCHILDREN_IDXI ON [SCLIBRARY].INV_GETITEMMATRIXCHILDREN_A(ITEMNUMBER);

  /

--RuleValues temporary table
 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].PRO_EXCRESOLP4210VERRULE_A
 ("UNIQUEID" NUMBER,"HIERARCHY" NUMBER, "RULETYPE" NVARCHAR2(2))  
   ON COMMIT PRESERVE ROWS;


  /
-- Create Tables Section
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].SEC_GETSECURITYAUDITLIST_A
    ("SCUSERID" NUMBER, "SCUSERNAME" NVARCHAR2(40), "MACHINEKEY" NVARCHAR2(15), 
    "ACTIONDATE" NUMBER, "ACTIONTIME" NUMBER, "APPNAME" NVARCHAR2(40), 
    "APPSOURCE" NVARCHAR2(500), "ACTIONDESC" NVARCHAR2(40), 
    "ACTIONPARAMS" NVARCHAR2(256), "ADDITIONALDETAIL" NCLOB, "USERID" NVARCHAR2(10), 
    "PROGRAMID" NVARCHAR2(10), "WORKSTATIONID" NVARCHAR2(10))  
ON COMMIT PRESERVE ROWS;





  /
-- Create Tables Section

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].CST_GETCUSTOMERINFOFNC_A ("AIAN8" 
    NUMBER, "AICO" NVARCHAR2(5), "AIURRF" 
    NVARCHAR2(15), "AIBADT" NVARCHAR2(1), 
    "AICMGR" NVARCHAR2(10), "AICARS" NUMBER,
    "AITXA1" NVARCHAR2(10), "AIEXR1" NVARCHAR2(2),
    "AIPORQ" NVARCHAR2(1), "AIAPRC" NUMBER, 
    "AIACL" NUMBER, "AIDAOJ" NUMBER, 
    "AITRAR" NVARCHAR2(3), "AIASTY" NUMBER, 
    "AISPYE" NUMBER, "AICPGP" NVARCHAR2(8), 
    "AIBACK" NVARCHAR2(1), "AICUSTS" NVARCHAR2(1),
    "AIDEL1" NVARCHAR2(30), "AIDEL2" NVARCHAR2(30),
    "AIEDF2" NVARCHAR2(30),
	"AIMINO" NUMBER,	
	"AIMAXO" NUMBER	)  
    ON COMMIT PRESERVE ROWS;



  /
-- Create Tables Section
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].CLB_GETMEMBERSHIPLIST_A 
    (
"ADDRESSNUMBER" NUMBER, 
"PARENTADDRESSNUMBER" NUMBER, 
"ALPHANAME" NVARCHAR2(100), 
"MLNAM" NVARCHAR2(100), 
"ADDL1"     NVARCHAR2(100), 
"ADDL2" NVARCHAR2(100),
"ADDL3" NVARCHAR2(100), 
"ADDL4" NVARCHAR2(100), 
"CITY" NVARCHAR2(100), 
"STATE"     NVARCHAR2(100), 
"ZIPCD" NVARCHAR2(100), 
"CNTRY" NVARCHAR2(100), 
"SHICTCTID" NUMBER,
"FIRSTNAME" NVARCHAR2(100),
"MDLNAME"     NVARCHAR2(100),
"LSTNAME" NVARCHAR2(100),
"NKNAME"     NVARCHAR2(100),
"ADRSFLAG" NUMBER, 
"AIDEL1"     NVARCHAR2(30), 
"AIDEL2" NVARCHAR2(30), 
"STATUS" NVARCHAR2(2), 
"SELECTED" NVARCHAR2(2), 
"PHONE" NVARCHAR2(50), 
"AlternateAddressKey" NVARCHAR2(20),
"TotalRowCount" NUMBER)
   ON COMMIT PRESERVE ROWS ;



  /
-- Create Tables Section

--COM_GETSALESORDERINFO_BILLTO
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETSALESORDINF_BILLTO_A
(
	"MAILINGNAME" NVARCHAR2(40), "ADDRESSLINE1" NVARCHAR2(40),
    "ADDRESSLINE2" NVARCHAR2(40), "ADDRESSLINE3" NVARCHAR2(40),
    "ADDRESSLINE4" NVARCHAR2(40), "CITY" NVARCHAR2(25), "STATE"
    NVARCHAR2(3), "ZIPCODE" NVARCHAR2(12), "COUNTRY" NVARCHAR2(3)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETSALESORDERINFO_Z_A
(
	"SCBILLTONUMBER" NUMBER, "SCSHIPTONUMBER" NUMBER,
    "ADDRESSBOOKTYPE" NUMBER, "DELIVERYINST1" NVARCHAR2(30),
    "DELIVERYINST2" NVARCHAR2(30), "CUSTOMERPO" NVARCHAR2(25),
    "ORDERCOMPANY" NVARCHAR2(5), "ORDERTYPE" NVARCHAR2(2),
    "ORDERNUMBER" NUMBER, "ORDERDATE" NUMBER, "REQUESTEDDATE"
    NUMBER, "MARKETINGCODE" NVARCHAR2(30), "HOLDORDERCODE"
    NVARCHAR2(2), "CURRENCYCODE" NVARCHAR2(3), "CURRENCYMODE"
    NVARCHAR2(1), "CURRENCYDESC" NVARCHAR2(30),
	"ISORDERRESTRICTED" NVARCHAR2(1), "ORDERHEADERCOMPANY" NVARCHAR2(5),
    "ISFREIGHTON" NVARCHAR2(3), "BASECURRENCYCODE" NVARCHAR2(3), "BASECURRENCYDESC" NVARCHAR2(30), "PAYMENTINSTRUMENT" NVARCHAR2(2)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETSALESORDERINFO_Z_B
(
	"ORDERCOMPANY"			NVARCHAR2(5),
	"ORDERTYPE"				NVARCHAR2(2),
    "ORDERNUMBER"			NUMBER,
	"LINENUMBER"			NUMBER, 
	"TRANSACTIONDATE"		NUMBER,
	"REQUESTEDDATE"			NUMBER,
    "LINETYPE"				NVARCHAR2(2),
	"NEXTSTATUS"			NVARCHAR2(3),
	"LASTSTATUS"			NVARCHAR2(3),
    "TAXABLEYN"				NVARCHAR2(1), 
	"TAXAREA"				NVARCHAR2(10),
    "TAXEXPLANATIONCODE"	NVARCHAR2(2),
	"DATEINVOICE"			NUMBER,
	"INVOICECOMPANY"		NVARCHAR2(5),
	"INVOICENUMBER"			NUMBER,
	"INVOICETYPE"			NCHAR(2),
	"SHIPTOID"				NUMBER, 
	"SCSHIPTONUMBER"		NUMBER, 
	"SHIPTONAME"			NVARCHAR2(40),
    "COSTCENTER"			NVARCHAR2(12),
	"COSTCENTERHEADER"		NVARCHAR2(12),
    "ITEMCROSSREFNUMBER"	NVARCHAR2(25),
	"DESCRIPTION1"			NVARCHAR2(30),
	"DESCRIPTION2"			NVARCHAR2(30),
	"URL"					NVARCHAR2(256),
    "SHIPPINGQUANTITY"		NUMBER,
	"SHIPPEDQUANTITY"		NUMBER,
	"UNITOFMEASURE"			NVARCHAR2(2),
    "PRICINGUNITOFMEASURE"	NVARCHAR2(2),
    "BACKORDEREDQUANTITY"	NUMBER,
	"CANCELEDQUANTITY"		NUMBER,
    "AMOUNTUNITPRICE"		NUMBER,
	"FOREIGNUNITPRICE"		NUMBER,
    "AMOUNTEXTPRICE"		NUMBER,
	"FOREIGNEXTPRICE"		NUMBER,
    "INVENTORYINTERFACE"	NVARCHAR2(1),
	"CARRIERID"				NUMBER,
    "MODEOFTRANSPORTATION"	NVARCHAR2(3),
	"IDENTIFIERSHORTITEM"   NUMBER,
	"LONGITEMNUMBER"		NVARCHAR2(25),
    "AUXITEMNUMBER"			NVARCHAR2(25),
    "ISINVOICERESTRICTED"	NVARCHAR2(1),
    "SHIPLINENUMBER"		NUMBER,
	"OVERRIDEPRICE"			NVARCHAR2(2),
    "STOCKINGTYPE"			NVARCHAR2(1),
    "RELATEDKITITEMNO"		NVARCHAR2(16),
    "KITMASTERLINENO"		NUMBER,
	"COMPONENTLINENUMBER"	NUMBER,
	"SHIPPEDDATE"			NUMBER,
	"LOCATION"				NVARCHAR2(20),
	"LOTNUMBER"				NVARCHAR2(30),
	"ISFREEGOOD"			NVARCHAR2(2),
	"PARENTLINENO"			NUMBER,
	"ISBASKETREPRICING"		NVARCHAR2(2)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETTEMPOORDERFILELIST_A
(
	"RECORDUNIQUEID" NUMBER, "DATEINSERT" NUMBER, "TIMEINSERT"
    NUMBER, "REGISTERID" NVARCHAR2(12), "INSTALLATIONID"
    NVARCHAR2(3), "USERINSERT" NUMBER, "DOCUMENTTYPE" NVARCHAR2(2),
    "REFERENCEID" NVARCHAR2(30), "FILENAME" NVARCHAR2(255),
    "STATUS" NVARCHAR2(5), "USERID" NVARCHAR2(10), "PROGRAMID"
    NVARCHAR2(10), "WORKSTATIONID" NVARCHAR2(10), "LASTDATEUPDATED"
    NUMBER, "LASTTIMEUPDATED" NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETINVOICEORDERDETAIL_A
(
	"ORDERCOMPANY"			NCHAR(5), 
	"ORDERTYPE"				NCHAR(2),
    "ORDERNUMBER"			NUMBER, 
	"LINENUMBER"			NUMBER, 
	"TRANSACTIONDATE"		NUMBER(6,0), 
	"REQUESTEDDATE"			NUMBER(6,0), 
	"LINETYPE"				NCHAR(2),
    "NEXTSTATUS"			NCHAR(3), 
	"LASTSTATUS"			NCHAR(3), 
	"TAXABLEYN"				NCHAR(1), 
	"TAXAREA"				NCHAR(10), 
	"TAXEXPLANATIONCODE"	NCHAR(2),
	"DATEINVOICE"			NUMBER,
    "INVOICECOMPANY"		NCHAR(5), 
	"INVOICENUMBER"			NUMBER,
    "INVOICETYPE"			NCHAR(2), 
	"SHIPTOID"				NUMBER, 
	"SCSHIPTONUMBER"		NUMBER,
    "SHIPTONAME"			NCHAR(40),
	"COSTCENTER"			NCHAR(12),
    "COSTCENTERHEADER"		NCHAR(12), 
	"ITEMCROSSREFNUMBER"	NCHAR(25), 
	"DESCRIPTION1"			NCHAR(30), 
	"DESCRIPTION2"			NCHAR(30), 
	"SHIPPINGQUANTITY"		NUMBER,
    "SHIPPEDQUANTITY"		NUMBER, 
	"UNITOFMEASURE"			NCHAR(2), 
	"PRICINGUNITOFMEASURE"	NCHAR(2),
    "BACKORDEREDQUANTITY"	NUMBER, 
	"CANCELEDQUANTITY"		NUMBER,
    "AMOUNTUNITPRICE"		NUMBER, 
	"FOREIGNUNITPRICE"		NUMBER,
    "AMOUNTEXTPRICE"		NUMBER, 
	"FOREIGNEXTPRICE"		NUMBER,
    "INVENTORYINTERFACE"	NCHAR(1), 
	"CARRIERID"				NUMBER,
    "MODEOFTRANSPORTATION"	NCHAR(3), 
	"IDENTIFIERSHORTITEM"	NUMBER, 
	"LONGITEMNUMBER"		NCHAR(25),
	"AUXITEMNUMBER"			NCHAR(25),
    "ISINVOICERESTRICTED"	NVARCHAR2(1),
    "SHIPLINENUMBER"		NUMBER,
    "STOCKINGTYPE"			NCHAR(1),
    "RELATEDKITITEMNO"		NCHAR(8),
    "KITMASTERLINENO"		NUMBER, 
	"OVERRIDEPRICE"			NCHAR(1), 
	"COMPONENTLINENUMBER"	NUMBER,
	"SHIPPEDDATE"			NUMBER(6,0), 
	"LOCATION"				NCHAR(20), 
	"LOTNUMBER"				NCHAR(30),
	"ISBASKETREPRICING"		NVARCHAR2(2)
) ON COMMIT PRESERVE ROWS;

--COM_GetSalesOrderRecentList
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETSALESORDERRECENT_A
(
    "ORDERNUMBER" NUMBER, "ORDERTYPE" NVARCHAR2(3),
    "ORDERCOMPANY" NVARCHAR2(5), "ORDERDATE" NUMBER,
    "CURRENCYCODE" NVARCHAR2(3), "CURRENCYMODE" NVARCHAR2(2), "HOLDCODE" NVARCHAR2(2),
    "PRODUCTTOTAL" NUMBER, "PRODUCTTOTALFOREIGN" NUMBER,
     "QUANTITYORDERED" NUMBER,"BASECURRENCYCODE" NVARCHAR2(3)
) ON COMMIT PRESERVE ROWS;

-- COM_GETRETURNORDHEADSRCHLIST
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETRTNORDHEADSRCHLIST_A
(
	"RETURNNUMBER"			NUMBER,
	"RETURNTYPE"			NVARCHAR2(3),
	"RETURNCOMPANY"			NVARCHAR2(5),
	"CUSTOMERREFERENCE"		NVARCHAR2(25),
	"TRANSACTIONDATE"		NUMBER,
	"ORIGINALORDERCOMPANY"	NVARCHAR2(5),
	"ORIGINALORDERNUMBER"	NVARCHAR2(8),
	"ORIGINALORDERTYPE"		NVARCHAR2(2)
) ON COMMIT PRESERVE ROWS;

--COM_GetReturnOrderInfo
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETRETURNORDERINFO_A
(
	"SCBILLTONUMBER"		NUMBER,
	"SCSHIPTONUMBER"		NUMBER,
	"ADDRESSBOOKTYPE"		NUMBER,
	"CUSTOMERPO"			NVARCHAR2(25),
	"RETURNCOMPANY"			NVARCHAR2(5),
	"RETURNTYPE"			NVARCHAR2(2),
	"RETURNNUMBER"			NUMBER,
	"TRANSACTIONDATE"		NUMBER,
	"CURRENCYCODE"			NVARCHAR2(3),
	"CURRENCYMODE"			NVARCHAR2(1),
	"CURRENCYDESC"			NVARCHAR2(30),
	"BASECURRENCY"			NVARCHAR2(3),
	"BASECURRENCYDESC"		NVARCHAR2(30),
	"PAYMENTINSTRUMENT"		NVARCHAR2(2),
	"HOLDORDERCODE"			NVARCHAR2(2),
	"REASONCODE"			NVARCHAR2(3)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETRETURNORDERINFO_B
(
	"RETURNCOMPANY"			NVARCHAR2(5),
	"RETURNTYPE"			NVARCHAR2(2),
	"RETURNNUMBER"			NUMBER,
	"LINENUMBER"			NUMBER,
	"TRANSACTIONDATE"		NUMBER,
	"LINETYPE"				NVARCHAR2(2),
	"NEXTSTATUS"			NVARCHAR2(3),
	"LASTSTATUS"			NVARCHAR2(3),
	"TAXABLEYN"				NVARCHAR2(1),
	"TAXAREA"				NVARCHAR2(10),
	"TAXEXPLANATIONCODE"	NVARCHAR2(5),
	"ORIGINALORDERCOMPANY"	NVARCHAR2(5),
	"ORIGINALORDERNUMBER"	NVARCHAR2(8),
	"ORIGINALORDERTYPE"		NVARCHAR2(2),
	"SHIPTOID"				NUMBER,
	"COSTCENTER"			NVARCHAR2(12),
	"COSTCENTERHEADER"		NVARCHAR2(12),
	"ITEMCROSSREFNUMBER"	NVARCHAR2(25),
	"DESCRIPTION1"			NVARCHAR2(30),
	"DESCRIPTION2"			NVARCHAR2(30),
	"URL"					NVARCHAR2(256),
	"SHIPPINGQUANTITY"		NUMBER,
	"SHIPPEDQUANTITY"		NUMBER,
	"UNITOFMEASURE"			NVARCHAR2(2),
	"PRICINGUNITOFMEASURE"	NVARCHAR2(2),
	"BACKORDEREDQUANTITY"	NUMBER,
	"CANCELEDQUANTITY"		NUMBER,
	"AMOUNTUNITPRICE"		NUMBER,
	"FOREIGNUNITPRICE"		NUMBER,
	"AMOUNTEXTPRICE"		NUMBER,
	"FOREIGNEXTPRICE"		NUMBER,
	"INVENTORYINTERFACE"	NVARCHAR2(1),
	"CARRIERID"				NUMBER,
	"MODEOFTRANSPORTATION"	NVARCHAR2(3),
	"IDENTIFIERSHORTITEM"	NUMBER,
	"LONGITEMNUMBER"		NVARCHAR2(25),
	"AUXITEMNUMBER"			NVARCHAR2(25),
	"ISORDERRESTRICTED"		NVARCHAR2(1),
	"OVERRIDEPRICE"			NVARCHAR2(2),
	"STOCKINGTYPE"			NVARCHAR2(1),
	"RELATEDKITITEMNO"		NVARCHAR2(16),
    "KITMASTERLINENO"		NUMBER,
	"COMPONENTLINENUMBER"	NUMBER

) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETORDERSHIPCONFINFO_A
(
	"SCBILLTONUMBER" NUMBER,
	"SCSHIPTONUMBER" NUMBER,
    "ADDRESSBOOKTYPE" NUMBER,
	"DELIVERYINST1" NVARCHAR2(30),
    "DELIVERYINST2" NVARCHAR2(30),
	"CUSTOMERPO" NVARCHAR2(25),
    "ORDERCOMPANY" NCHAR(5),
	"ORDERTYPE" NCHAR(2),
    "ORDERNUMBER" NUMBER,
	"ORDERDATE" NUMBER,
	"REQUESTEDDATE" NUMBER,
	"MARKETINGCODE" NVARCHAR2(30),
	"HOLDORDERCODE" NVARCHAR2(2),
	"CURRENCYCODE" NVARCHAR2(3),
	"CURRENCYMODE" NVARCHAR2(1),
	"CURRENCYDESC" NVARCHAR2(30),
	"ISFREIGHTON" NVARCHAR2(3)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETORDERSHIPCONFINFO_B
(
	"ORDERCOMPANY" NCHAR(5),
	"ORDERTYPE" NCHAR(2),
	"ORDERNUMBER" NUMBER,
	"LINENUMBER" NUMBER,
	"TRANSACTIONDATE" NUMBER,
	"REQUESTEDDATE"     NUMBER,
    "LINETYPE" NVARCHAR2(2),
	"NEXTSTATUS" NVARCHAR2(3),
	"LASTSTATUS" NVARCHAR2(3),
    "TAXABLEYN" NVARCHAR2(1),
	"TAXAREA" NVARCHAR2(10),
    "TAXEXPLANATIONCODE" NVARCHAR2(2),
	"INVOICECOMPANY"     NVARCHAR2(5),
	"INVOICENUMBER" NUMBER,
	"INVOICETYPE"   NVARCHAR2(2),
	"SHIPTOID" NUMBER,
	"SCSHIPTONUMBER" NUMBER,
    "COSTCENTER" NVARCHAR2(12),
	"COSTCENTERHEADER" NVARCHAR2(12),
    "ITEMCROSSREFNUMBER" NVARCHAR2(25),
	"DESCRIPTION1"   NVARCHAR2(30),
	"DESCRIPTION2" NVARCHAR2(30),
    "QUANTITYORDERED" NUMBER,
	"SHIPPEDQUANTITY" NUMBER,
	"UNITOFMEASURE" NVARCHAR2(2),
    "PRICINGUNITOFMEASURE" NVARCHAR2(2),
    "BACKORDEREDQUANTITY" NUMBER,
	"CANCELEDQUANTITY" NUMBER,
    "AMOUNTUNITPRICE" NUMBER,
	"FOREIGNUNITPRICE" NUMBER,
    "AMOUNTEXTPRICE" NUMBER,
	"FOREIGNEXTPRICE" NUMBER,
    "INVENTORYINTERFACE" NVARCHAR2(1),
	"CARRIERID" NUMBER,
	"CARRIERNAME" NVARCHAR2(40),
    "MODEOFTRANSPORTATION" NVARCHAR2(3),
	"IDENTIFIERSHORTITEM"  NUMBER,
	"LONGITEMNUMBER" NVARCHAR2(25),
    "AUXITEMNUMBER" NVARCHAR2(25),
    "SHIPLINENUMBER" NUMBER,
	"STOCKINGTYPE" NVARCHAR2(1),
    "RELATEDKITITEMNO" NVARCHAR2(16),
    "KITMASTERLINENO" NUMBER,
	"COMPONENTLINENUMBER" NUMBER,
	"SALESREPORTINGCODE1" NVARCHAR2(3),
	"SALESREPORTINGCODE2" NVARCHAR2(3),
	"SALESREPORTINGCODE3" NVARCHAR2(3),
	"SALESREPORTINGCODE4" NVARCHAR2(3),
	"SALESREPORTINGCODE5" NVARCHAR2(3),
	"PRICEADJUSTMENTSCHEDULEN"  NVARCHAR2(8),
	"CONTRACTNUMBERDISTRIBUTI" NVARCHAR2(12),
	"PAYMENTTERMSCODE" NVARCHAR2(3),
	"PAYMENTTERMSCODEDESC" NVARCHAR2(30),
	"LINEOFBUSINESS" NVARCHAR2(3),
	"ENDUSE" NVARCHAR2(3),
	"DUTYSTATUS" NVARCHAR2(2),
	"PRICECODE1" NVARCHAR2(2),
	"PRICECODE2" NVARCHAR2(2),
	"PRICECODE3" NVARCHAR2(2)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETSALESORDERSHIPMENTS_A
(
	"ORDERCOMPANY"		NCHAR(5),
	"ORDERTYPE"			NCHAR(2),
	"ORDERNUMBER"		NUMBER,
	"COSTCENTER"		NCHAR(12),
	"SHIPLINENUMBER"	NUMBER,
	"SCSHIPTONUMBER"	NUMBER,
	"LINETYPE"			NCHAR(2)
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GetSOReturnLineSrchListA
(
	"ORDERNUMBER"				NUMBER,
	"ORDERTYPE"					NCHAR(2),
	"COMPANY"					NCHAR(5),
	"LINENUMBER"				NUMBER,
	"ITEMDESCRIPTION1"			NCHAR(30),
	"ITEMDESCRIPTION2"			NCHAR(30),
	"UNITPRICE"					NUMBER,
	"FOREIGNUNITPRICE"			NUMBER,
	"QUANTITY"					NUMBER,
	"SHIPPEDQUANTITY"			NUMBER,
	"RETURNEDQUANTITY"			NUMBER,
	"DISPLAYITEMNUMBER"			NCHAR(25),
	"ITEMNUMBER"				NUMBER,
	"UNITOFMEASURE"				NCHAR(2),
	"SCBILLTONUMBER"			NUMBER,
	"SCBILLTOCONTACTID"			NUMBER,
	"ADDRESSBOOKTYPE"			NUMBER,
	"NEXTSTATUS"				NCHAR(3),
	"TAXABLEYN"					NCHAR(1),
	"CURRENCYMODE"				NCHAR(1),
	"LOCATION"					NCHAR(20),
	"LOTNUMBER"					NCHAR(30),
	"TAXEDUNITPRICE"			NUMBER,
	"FOREIGNTAXEDUNITPRICE"		NUMBER,
	"ORDERACTUALDELIVERYDATE"	NUMBER(6,0),
	"USETAXEDPRICES"			NCHAR(1)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GetSOConfiguredLineList_A
(
	"CONFIGURATORID" NUMBER,
	"BRANCHPLANT"    NVARCHAR2(12),
	"LINENUMBER"	 NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETCROSSSEGMENTRULESLIST_A
(
	ItemNumber NUMBER, 
	BranchPlant NCHAR(12)
) ON COMMIT PRESERVE ROWS;

--COM_GetInvAutoPayRuleList
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETINVAUTOPAYRULELIST_A
(
    "RULEID" NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].COM_GETINVAUTOPAYRULELIST_B
(
    "RULEID" NUMBER
) ON COMMIT PRESERVE ROWS;


  /
-- Create Tables Section

-- QTS_GetQuoteOrderInfo_Z
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].QTS_GETQUOTEORDERINFO_Z_A
    ("SCBILLTONUMBER" NUMBER, "SCSHIPTONUMBER" NUMBER, 
    "ADDRESSBOOKTYPE" NUMBER, "DELIVERYINST1" NCHAR(30), 
    "DELIVERYINST2" NCHAR(30), "CUSTOMERPO" NCHAR(25), 
    "ORDERCOMPANY" NCHAR(5), "ORDERTYPE" NCHAR(2), 
    "QUOTENUMBER" NUMBER, "ORDERDATE" NUMBER(6,0), "CANCELDATE" NUMBER(6,0), "REQUESTEDDATE" 
    NUMBER(6,0), MARKETINGCODE		NCHAR ( 30 ),
    "MEMBERSHIPID" NUMBER,"PERCENTAGEDISCOUNT" NUMBER,"DISCOUNTTYPE" NUMBER(15,0),
    "REASONCODE" NCHAR(3),
    "CURRENCYCODE" NCHAR(3), "CURRENCYMODE" 
    NCHAR(1), "CURRENCYDESC" NCHAR(30),
	"ORDERHEADERCOMPANY" NCHAR(5),"CONTACTID" NUMBER)
    ON COMMIT PRESERVE ROWS;    
    
CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].QTS_GETQUOTEORDERINFO_Z_B
    ("ORDERCOMPANY" NCHAR(5), "ORDERTYPE" NCHAR(2), 
    "QUOTENUMBER" NUMBER, "LINENUMBER" NUMBER, "TRANSACTIONDATE" 
	NUMBER(6,0),"REQUESTEDDATE"     NUMBER(6,0),
    "LINETYPE" NCHAR(2), "TAXABLEYN" NCHAR(1), "TAXAREA" NCHAR(10), 
    "TAXEXPLANATIONCODE" NCHAR(2),
    "SHIPTOID" NUMBER, "SCSHIPTONUMBER" NUMBER,
    "COSTCENTER" NCHAR(12), "COSTCENTERHEADER" NCHAR(12), 
    "ITEMCROSSREFNUMBER" NCHAR(25), "DESCRIPTION1" 
    NCHAR(30), "DESCRIPTION2" NCHAR(30), "URL" NVARCHAR2(256), 
    "QUANTITYORDERED" NUMBER, "SHIPPEDQUANTITY" NUMBER, "UNITOFMEASURE" NCHAR(2),
    "PRICINGUNITOFMEASURE" NCHAR(2),
    "BACKORDEREDQUANTITY" NUMBER, "CANCELEDQUANTITY" NUMBER, 
    "AMOUNTUNITPRICE" NUMBER, "FOREIGNUNITPRICE" NUMBER, 
    "AMOUNTEXTPRICE" NUMBER, "FOREIGNEXTPRICE" NUMBER, 
    "INVENTORYINTERFACE" NCHAR(1), "IDENTIFIERSHORTITEM" 
    NUMBER, "LONGITEMNUMBER" NCHAR(25),  
    "AUXITEMNUMBER" NCHAR(25),"NEXTSTATUS" NCHAR(3), "LASTSTATUS" NCHAR(3), "OVERRIDEPRICE" NCHAR(1),
	"STOCKINGTYPE" NCHAR(1), "RELATEDKITITEMNO" NCHAR(8), "KITMASTERLINENO" NUMBER, "COMPONENTLINENUMBER" NUMBER, "SHIPLINENUMBER" NUMBER(15,0))  
    ON COMMIT PRESERVE ROWS;


  /
-- Create Tables Section

 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].POS_GETRECEIPTDETAIL_A ("RECEIPTID"
    NVARCHAR2(10), "INSTALLATIONID" NVARCHAR2(3), "REGISTERID" 
    NVARCHAR2(12), "XMLBODY" NCLOB)  
 ON COMMIT PRESERVE ROWS ;

--POS_GetDrawerPayment
 CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].POS_GETDRAWERPAYMENT_A (
	"RC$9REGID"			NVARCHAR2(12),
	"RC$9DRAW"			NUMBER,
	"RCEDBT"			NVARCHAR2(15),
	"DPRYIN"			NVARCHAR2(1),
	"DPCARD"			NVARCHAR2(4),
	"DPCRCD"			NVARCHAR2(3),
	"OPENINGBALANCE"	NUMBER,
	"LEFTINDRAWER"		NUMBER,
	"TOTALSPERCASHIER"	NUMBER,
	"DP$9AATR"			NUMBER
 )  
   ON COMMIT PRESERVE ROWS ; 
  /
-- Create Tables Section

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].ECO_GETWEBSITEMSTVIEWITMS_A
	("MV$9INID"	NVARCHAR2(3),"MVITM" NUMBER,"MVCNTF" NUMBER,
	"MVUPMJ" NUMBER,"MVUPMT" NUMBER,"IMDSC1" NVARCHAR2(30),
	"IMDSC2" NVARCHAR2(30),"IMITM" NVARCHAR2(25))
ON COMMIT PRESERVE ROWS ;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].ECO_GETMIGRATIONPRODUCTLIST_A
(
	"SHORTITEMNUMBER"	NUMBER,
	"LONGITEMNUMBER" NCHAR(25),
	"TBLSTOREID" NCHAR(3),
	"DESCRIPTION" NCHAR(61),
	"HTMLCONTENT" NCLOB,
	"EXTERNALURL" NVARCHAR2(256),
	"KEYWORDS" NVARCHAR2(310),
	"METATITLE" NVARCHAR2(255),
	"METADESCRIPTION" NVARCHAR2(256),
	"SCTYPE" NCHAR(1),
	"BRANCHPLANT" NCLOB,
	"HASWEBCONTENT"	INT
)
ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].ECO_GETMIGRACATALOGASSIGNLST_A 
(
	"CATALOGID" NCHAR(3),
	"ASSIGNMENTID" NUMBER,
    "ASSIGNMENTTYPE" NUMBER(15,0), 
	"CATEGORYCODE" NCHAR(10),
	"ASSIGNMENTVALUE" NCHAR(40), 
	"DESCRIPTION" NVARCHAR2(256)
)
ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].ECO_GETMIGRAATTRIBUTELIST_A 
(
	"ATTRIBUTEID" NCHAR(10),
	"DESCRIPTION" NCHAR(30),
	"ATTRIBUTETYPE" NUMBER,
	"TOTALROWCOUNT" INT
)
ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].ECO_GETMIGRAATTGROUPLIST_A 
(
	"TEMPLATEID" NCHAR(10),
	"DESCRIPTION" NCHAR(30),
	"TOTALROWCOUNT" INT
)
ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE [SCLIBRARY].ECO_GETMIGRACATALOGNODELIST_A 
(
	"CATALOGID" NCHAR(3),
	"NODEID" NUMBER
)
ON COMMIT PRESERVE ROWS;


  /
