/***********************************************************************************************************************/
--F42119
/***********************************************************************************************************************/
BEGIN
 IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
  WHERE INDEX_NAME='SC_F42119_01'
		AND TABLE_NAME = 'F42119'
		AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
	DROP INDEX [SCDATA].SC_F42119_01;
 END IF;
END;
  
CREATE INDEX [SCDATA].SC_F42119_01 
	ON [SCDATA].F42119 (
	SDLNTY ASC,
	SDKCOO ASC,
	SDDOCO ASC,
	SDDCTO ASC,
	SDLNID ASC,
	SDSHAN ASC,
	SDITM ASC,
	SDNXTR ASC,
	SDLTTR ASC
);
 
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42119_02'
				AND TABLE_NAME = 'F42119'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42119_02;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F42119_02 
        ON [SCDATA].F42119(
        SDKCOO ASC, 
        SDSHAN ASC, 
        SDDCTO ASC, 
        SDDOCO ASC
 ) ;
 
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42119_03'
				AND TABLE_NAME = 'F42119'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42119_03;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F42119_03 
        ON [SCDATA].F42119(
        SDSHAN ASC, 
        SDLNTY ASC
 ) ;


BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42119_04'
				AND TABLE_NAME = 'F42119'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42119_04;
	END IF;
END;
  
CREATE INDEX [SCDATA].SC_F42119_04
	ON [SCDATA].F42119 (
	SDLNTY ASC,
	SDLTTR ASC,
	SDKCOO ASC,
	SDDOCO ASC,
	SDDCTO ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42119_05'
				AND TABLE_NAME = 'F42119'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42119_05;
	END IF;
END;
 
CREATE INDEX [SCDATA].SC_F42119_05
	ON [SCDATA].F42119 ( 
	SDOORN ASC , 
	SDOGNO ASC , 
	SDOCTO ASC , 
	SDOKCO ASC , 
	SDDCTO ASC 
); 

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42119_06'
				AND TABLE_NAME = 'F42119'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42119_06;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F42119_06 
    ON [SCDATA].F42119(
    SDDOC ASC, 
    SDDCT ASC, 
    SDKCO ASC
) ;


BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42119_07'
				AND TABLE_NAME = 'F42119'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42119_07;
	END IF;
END; 
  
CREATE INDEX [SCDATA].SC_F42119_07 
	ON [SCDATA].F42119 (
	SDKCOO ASC,
	SDDCTO ASC,
	SDLNTY ASC,
	SDDOCO ASC,
	SDLNID ASC,
	SDMCU ASC,
	SDAN8 ASC,
	SDSHAN ASC,
	SDTRDJ ASC,
	SDADDJ ASC,
	SDITM ASC,
	SDLITM ASC,
	SDAITM ASC,
	SDLOCN ASC,
	SDLOTN ASC,
	SDDSC1 ASC,
	SDDSC2 ASC,
	SDNXTR ASC,
	SDLTTR ASC,
	SDUOM ASC,
	SDUORG ASC,
	SDSOQS ASC,
	SDUPRC ASC,
	SDAEXP ASC,
	SDTAX1 ASC,
	SDFUP ASC,
	SDFEA ASC
);
  
/***********************************************************************************************************************/
--F4211
/***********************************************************************************************************************/

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4211_01'
				AND TABLE_NAME = 'F4211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4211_01;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4211_01 
	ON [SCDATA].F4211 (
	SDLNTY ASC,
	SDDOCO ASC,
	SDDCTO ASC,
	SDLNID ASC,
	SDSHAN ASC,
	SDITM ASC,
	SDNXTR ASC,
	SDLTTR ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4211_07'
				AND TABLE_NAME = 'F4211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4211_07;
	END IF;
END; 
  
CREATE INDEX [SCDATA].SC_F4211_07 
	ON [SCDATA].F4211 (
	SDKCOO ASC,
	SDDCTO ASC,
	SDLNTY ASC,
	SDLNID ASC,
	SDMCU ASC,
	SDAN8 ASC,
	SDSHAN ASC,
	SDTRDJ ASC,
	SDADDJ ASC,
	SDITM ASC,
	SDLITM ASC,
	SDAITM ASC,
	SDLOCN ASC,
	SDLOTN ASC,
	SDDSC1 ASC,
	SDDSC2 ASC,
	SDNXTR ASC,
	SDLTTR ASC,
	SDUOM ASC,
	SDUORG ASC,
	SDSOQS ASC,
	SDUPRC ASC,
	SDAEXP ASC,
	SDTAX1 ASC,
	SDFUP ASC,
	SDFEA ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4211_02'
				AND TABLE_NAME = 'F4211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4211_02;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4211_02
    ON [SCDATA].F4211(
    SDKCOO ASC, 
    SDSHAN ASC, 
    SDDCTO ASC, 
    SDDOCO ASC
) ;

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4211_03'
				AND TABLE_NAME = 'F4211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4211_03;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4211_03 
    ON [SCDATA].F4211(
    SDSHAN ASC, 
    SDLNTY ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4211_04'
				AND TABLE_NAME = 'F4211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4211_04;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F4211_04 
	ON [SCDATA].F4211 ( 
    SDKCOO ASC, 
    SDDCTO ASC, 
    SDDOCO ASC, 
    SDOORN ASC
 );   
 
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4211_05'
				AND TABLE_NAME = 'F4211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4211_05;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4211_05
	ON [SCDATA].F4211 ( 
	SDOORN ASC, 
	SDOGNO ASC, 
	SDOCTO ASC, 
	SDOKCO ASC, 
	SDDCTO ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4211_06'
				AND TABLE_NAME = 'F4211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4211_06;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F4211_06 
	ON [SCDATA].F4211 ( 
    SDLNTY ASC, 
    SDLTTR ASC, 
    SDKCOO ASC, 
    SDDOCO ASC, 
    SDDCTO ASC
    );

/***********************************************************************************************************************/
--F4201
/***********************************************************************************************************************/
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4201_07'
				AND TABLE_NAME = 'F4201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4201_07;
	END IF;
END; 
  
CREATE INDEX [SCDATA].SC_F4201_07 
	ON [SCDATA].F4201 (
	SHDCTO ASC,
	SHKCOO ASC,
	SHDOCO ASC,
	SHCO ASC,
	SHRORN ASC,
	SHRCTO ASC,
	SHAN8 ASC,
	SHSHAN ASC,
	SHDRQJ ASC,
	SHTRDJ ASC,
	SHVR01 ASC,
	SHDEL1 ASC,
	SHDEL2 ASC,
	SHHOLD ASC,
	SHOTOT ASC,
	SHCRRM ASC,
	SHCRCD ASC,
	SHFAP ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4201_01'
				AND TABLE_NAME = 'F4201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4201_01;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4201_01 
	ON [SCDATA].F4201 ( 
    SHKCOO ASC, 
    SHDCTO ASC, 
    SHDOCO ASC, 
    SHRYIN ASC, 
    SHCRRM ASC, 
    SHCRCD ASC
 );

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4201_02'
				AND TABLE_NAME = 'F4201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4201_02;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4201_02 
    ON [SCDATA].F4201 (
    SHDOCO  ASC, 
    SHAN8	ASC, 
    SHVR01  ASC, 
    SHDCTO  ASC, 
    SHKCOO  ASC
 );

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4201_03'
				AND TABLE_NAME = 'F4201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4201_03;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4201_03 
    ON [SCDATA].F4201 (
    SHKCOO  ASC, 
    SHAN8  ASC
  );

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4201_04'
				AND TABLE_NAME = 'F4201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4201_04;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4201_04 
    ON [SCDATA].F4201 (
	SHAN8  ASC,
	SHTRDJ  ASC,
	SHCO ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4201_05'
				AND TABLE_NAME = 'F4201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4201_05;
	END IF;
END;
 
CREATE INDEX [SCDATA].SC_F4201_05 
    ON [SCDATA].F4201 (
    SHKCOO  ASC, 
    SHTRDJ  ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F4201_06'
				AND TABLE_NAME = 'F4201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4201_06;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4201_06
    ON [SCDATA].F4201 (
	SHAN8  ASC,
	SHDCTO  ASC,
	SHCO ASC
);



/***********************************************************************************************************************/
--F42019
/***********************************************************************************************************************/
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_08'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_08;
	END IF;
END; 
  
CREATE INDEX [SCDATA].SC_F42019_08
	ON [SCDATA].F42019 (
	SHDCTO ASC,
	SHKCOO ASC,
	SHDOCO ASC,
	SHCO ASC,
	SHRORN ASC,
	SHRCTO ASC,
	SHAN8 ASC,
	SHSHAN ASC,
	SHDRQJ ASC,
	SHTRDJ ASC,
	SHVR01 ASC,
	SHDEL1 ASC,
	SHDEL2 ASC,
	SHHOLD ASC,
	SHOTOT ASC,
	SHCRRM ASC,
	SHCRCD ASC,
	SHFAP ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_01'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_01;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F42019_01 
	ON [SCDATA].F42019 (
	SHKCOO ASC,
	SHDCTO ASC,
	SHDOCO ASC,
	SHRYIN ASC,
	SHCRRM ASC,
	SHCRCD ASC
);

 
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_02'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_02;
	END IF;
END;  

CREATE INDEX [SCDATA].SC_F42019_02
    ON [SCDATA].F42019 (
    SHDOCO  ASC, 
    SHAN8  ASC, 
    SHVR01  ASC, 
    SHDCTO  ASC, 
    SHKCOO  ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_03'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_03;
	END IF;
END; 
 
CREATE INDEX [SCDATA].SC_F42019_03
    ON [SCDATA].F42019 (
    SHKCOO  ASC, 
    SHAN8  ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_04'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_04;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F42019_04 
    ON [SCDATA].F42019 (
	SHAN8  ASC,
	SHTRDJ  ASC,
	SHCO ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_05'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_05;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F42019_05
    ON [SCDATA].F42019 (
    SHKCOO  ASC, 
    SHTRDJ  ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_06'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_06;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F42019_06
    ON [SCDATA].F42019 (
	SHAN8  ASC,
	SHDCTO  ASC,
	SHCO ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F42019_07'
				AND TABLE_NAME = 'F42019'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F42019_07;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F42019_07
	ON [SCDATA].F42019 ( 
	SHAN8 ASC 
); 

/***********************************************************************************************************************/
--FQ674201
/***********************************************************************************************************************/

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_FQ674201_01'
				AND TABLE_NAME = 'FQ674201'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_FQ674201_01;
	END IF;
END;
  
CREATE INDEX [SCDATA].SC_FQ674201_01
	ON [SCDATA].FQ674201 (
	SHKCOO ASC,
	SHDOCO ASC,
	SHDCTO ASC,
	SHIDLN ASC,
	SH$9SHAN ASC,
	SHRCK7 ASC,
	SH$9TYP ASC,
	SH$9AN8 ASC
);

BEGIN
 IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
  WHERE INDEX_NAME='SC_FQ674201_02'
		AND TABLE_NAME = 'FQ674201'
		AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
	DROP INDEX [SCDATA].SC_FQ674201_02;
 END IF;
END;   
CREATE INDEX [SCDATA].SC_FQ674201_02 
	ON [SCDATA].FQ674201 ( 
	SH$9TYP ASC , 
	SH$9AN8 ASC , 
	SHKCOO ASC , 
	SHDCTO ASC , 
	SHDOCO ASC 
); 


/***********************************************************************************************************************/
--FQ674211
/***********************************************************************************************************************/

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_FQ674211_01'
				AND TABLE_NAME = 'FQ674211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_FQ674211_01;
	END IF;
END; 
  
CREATE INDEX [SCDATA].SC_FQ674211_01
	ON [SCDATA].FQ674211 (
	SD$9SHAN ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_FQ674211_02'
				AND TABLE_NAME = 'FQ674211'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_FQ674211_02;
	END IF;
END;  
CREATE INDEX [SCDATA].SC_FQ674211_02
	ON [SCDATA].FQ674211 (
	SD$9TYP ASC , 
	SDKCOO ASC , 
	SDDCTO ASC , 
	SDLNID ASC , 
	SDDOCO ASC
);

/***********************************************************************************************************************/
--FQ67008
/***********************************************************************************************************************/

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_FQ67008_01'
				AND TABLE_NAME = 'FQ67008'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_FQ67008_01;
	END IF;
END;  
  
CREATE INDEX [SCDATA].SC_FQ67008_01
	ON [SCDATA].FQ67008 (
	DR$9INID ASC,
	DR$9CNST ASC,
	DRKY ASC
);

/***********************************************************************************************************************/
--F03B11
/***********************************************************************************************************************/
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03B11_01'
				AND TABLE_NAME = 'F03B11'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA] .SC_F03B11_01;
	END IF;
END;
CREATE INDEX [SCDATA].SC_F03B11_01 
    ON [SCDATA].F03B11 (
    RPCRCD ASC, 
    RPCO   ASC, 
    RPAN8  ASC, 
    RPDOC  ASC, 
    RPDDJ  ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03B11_02'
				AND TABLE_NAME = 'F03B11'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03B11_02;
	END IF;
END;
CREATE INDEX [SCDATA].SC_F03B11_02
    ON [SCDATA].F03B11 (
    RPCRCD  ASC, 
    RPCO    ASC, 
    RPAN8   ASC, 
    RPDIVJ  ASC
 );


BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03B11_03'
				AND TABLE_NAME = 'F03B11'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03B11_03;
	END IF;
END;
CREATE INDEX [SCDATA].SC_F03B11_03
    ON [SCDATA].F03B11 (
    RPCRCD ASC, 
    RPCO   ASC, 
    RPAN8  ASC, 
    RPDCT  ASC, 
    RPDIVJ ASC
 );

/***********************************************************************************************************************/
--F03012
/***********************************************************************************************************************/

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03012_01 '
				AND TABLE_NAME = 'F03012'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03012_01;
	END IF;
END;
CREATE INDEX [SCDATA].SC_F03012_01
    ON [SCDATA].F03012 (
    AICO    ASC, 
    AIBADT  ASC, 
    AICUSTS ASC, 
    AIAN8   ASC
);

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03012_02'
				AND TABLE_NAME = 'F03012'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03012_02;
	END IF;
END;
CREATE INDEX [SCDATA].SC_F03012_02 
    ON [SCDATA].F03012 (
    AICO   ASC, 
    AIAN8  ASC, 
    AIBADT ASC
);

/***********************************************************************************************************************/
--F03B13Z1
/***********************************************************************************************************************/

BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03B13Z1_01'
				AND TABLE_NAME = 'F03B13Z1'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03B13Z1_01;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F03B13Z1_01 
	ON [SCDATA].F03B13Z1 (
	RUKCO ASC , 
	RUDCT ASC , 
	RUSFX ASC , 
	RUAN8 ASC , 
	RUDOC ASC 
);   


BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03B13Z1_02'
				AND TABLE_NAME = 'F03B13Z1'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03B13Z1_02;
	END IF;
END;
CREATE INDEX [SCDATA].SC_F03B13Z1_02
    ON [SCDATA].F03B13Z1(
    RUAN8 ASC, 
    RUEUPS ASC
);


BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03B13Z1_03'
				AND TABLE_NAME = 'F03B13Z1'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03B13Z1_03;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F03B13Z1_03
    ON [SCDATA].F03B13Z1(
    RUDOC ASC, 
    RUEUPS ASC
);

/***********************************************************************************************************************/
--F03B14
/***********************************************************************************************************************/
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
			WHERE INDEX_NAME='SC_F03B14_01'
				AND TABLE_NAME = 'F03B14'
				AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F03B14_01;
	END IF;
END;

CREATE INDEX [SCDATA].SC_F03B14_01
	ON [SCDATA].F03B14 (
	RZDCT ASC , 
	RZSFX ASC , 
	RZKCO ASC , 
	RZAN8 ASC , 
	RZDOC ASC 
); 

/***********************************************************************************************************************/
--F0901
/***********************************************************************************************************************/
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
		WHERE INDEX_NAME='SC_F0901_01'
			AND TABLE_NAME = 'F0901'
			AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F0901_01;
	END IF;
END;  

CREATE INDEX [SCDATA].SC_F0901_01 
	ON [SCDATA].F0901 ( 
	GMMCU ASC , 
	GMOBJ ASC , 
	GMSUB ASC , 
	GMAID ASC 
);

/***********************************************************************************************************************/
--F4104
/***********************************************************************************************************************/
BEGIN
	IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
		WHERE INDEX_NAME='SC_F4104_01'
			AND TABLE_NAME = 'F4104'
			AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
		DROP INDEX [SCDATA].SC_F4104_01;
	END IF;
END; 

CREATE INDEX [SCDATA].SC_F4104_01 
	ON [SCDATA].F4104 (
	IVXRT ASC , 
	IVEXDJ ASC 
);

/***********************************************************************************************************************/
--FQ67410
/***********************************************************************************************************************/
BEGIN
 IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
  WHERE INDEX_NAME='SC_FQ67410_01'
		AND TABLE_NAME = 'FQ67410'
		AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
	DROP INDEX [SCDATA].SC_FQ67410_01; END IF;
END;  

CREATE INDEX [SCDATA].SC_FQ67410_01 
	ON [SCDATA].FQ67410 (
	CH$9DS  ASC, 
	CH$9INID  ASC
);

/***********************************************************************************************************************/
--F41008
/***********************************************************************************************************************/
BEGIN
 IF EXISTS (SELECT  1  FROM QSYS2.SYSINDEXES
  WHERE INDEX_NAME='SC_F41008_01'
		AND TABLE_NAME = 'F41008'
		AND SYSTEM_TABLE_SCHEMA= '[SCDATA]') THEN
	DROP INDEX [SCDATA].SC_F41008_01; END IF;
END;  

CREATE INDEX [SCDATA].SC_F41008_01 
	ON [SCDATA].F41008(
	S0TMPL ASC, S0SEG1 ASC
);



